steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-southeast1-docker.pkg.dev/${PROJECT_ID}/llm-models/ollama-backend:latest', '.']
    timeout: '1800s'

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-southeast1-docker.pkg.dev/${PROJECT_ID}/llm-models/ollama-backend:latest']

# Set a longer timeout due to model download during build
timeout: '2700s'

options:
  machineType: 'E2_MEDIUM'

# Use a more powerful machine for faster builds
# options:
#   machineType: 'E2_HIGHCPU_32'

images:
  - 'asia-southeast1-docker.pkg.dev/${PROJECT_ID}/llm-models/ollama-backend:latest'
